baseURL: "https://brettloewen.github.io/Comp-2600-A2/"
title: My Blog
theme: [PaperMod]

params:
  homeInfoParams:
    Title: "Hello there \U0001F44B"
    Content: Welcome to my statically generated site

  socialIcons:
    - name: github
      url: "https://github.com/BrettLoewen/"